version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=baumhaus
      - MySQL_DATABASE=dbs_labor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=baumhaus
    ports:
      - 3307:3306

  app:
    container_name: dbs-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/dbs_labor
    #restart: on-failure